export const LOAD_BREEDS_LIST = 'LOAD_BREEDS_LIST';
//export const GET_BREEDS_LIST = 'GET_BREEDS_LIST';
export const LOAD_BREEDS_IMAGES = 'LOAD_BREEDS_IMAGES';
//export const GET_BREEDS_IMAGES = 'GET_BREEDS_IMAGES';
export const SELECT_CAT = 'SELECT_CAT';
export const CLEAR_BREEDS_IMAGES = 'CLEAR_BREEDS_IMAGES';
